# Generated by Django 3.1.5 on 2021-07-12 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume', models.CharField(max_length=264)),
                ('prenume', models.CharField(max_length=264)),
                ('email', models.EmailField(max_length=254)),
                ('parola', models.CharField(max_length=264)),
            ],
        ),
        migrations.CreateModel(
            name='Anunt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titlul', models.CharField(max_length=264)),
                ('imagine', models.ImageField(upload_to='')),
                ('descriere', models.TextField(max_length=624)),
                ('data_postarii', models.DateTimeField()),
                ('telefon', models.IntegerField()),
                ('categoria', models.CharField(max_length=264)),
            ],
        ),
        migrations.CreateModel(
            name='Copil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume', models.CharField(max_length=264)),
                ('prenume', models.CharField(max_length=264)),
                ('email', models.EmailField(max_length=254)),
                ('parola', models.CharField(max_length=264)),
            ],
        ),
    ]
