# Generated by Django 3.1.5 on 2022-01-11 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anuntadult',
            name='an_de_constructie',
        ),
        migrations.RemoveField(
            model_name='anuntadult',
            name='capacitate_motor',
        ),
        migrations.RemoveField(
            model_name='anuntadult',
            name='combustibil',
        ),
        migrations.RemoveField(
            model_name='anuntadult',
            name='compartimentare',
        ),
        migrations.RemoveField(
            model_name='anuntadult',
            name='culoare',
        ),
        migrations.RemoveField(
            model_name='anuntadult',
            name='cutie_de_viteze',
        ),
        migrations.RemoveField(
            model_name='anuntadult',
            name='etaj',
        ),
        migrations.RemoveField(
            model_name='anuntadult',
            name='marca',
        ),
        migrations.RemoveField(
            model_name='anuntadult',
            name='marime',
        ),
        migrations.RemoveField(
            model_name='anuntadult',
            name='mobilitatea_postului',
        ),
        migrations.RemoveField(
            model_name='anuntadult',
            name='nivelul_de_experienta',
        ),
        migrations.RemoveField(
            model_name='anuntadult',
            name='nivelul_de_studii',
        ),
        migrations.RemoveField(
            model_name='anuntadult',
            name='numar_de_camere',
        ),
        migrations.RemoveField(
            model_name='anuntadult',
            name='program_flexibil',
        ),
        migrations.RemoveField(
            model_name='anuntadult',
            name='rulaj',
        ),
        migrations.RemoveField(
            model_name='anuntadult',
            name='stare',
        ),
        migrations.RemoveField(
            model_name='anuntadult',
            name='suprafata_utila',
        ),
        migrations.RemoveField(
            model_name='anuntadult',
            name='teren',
        ),
        migrations.RemoveField(
            model_name='anuntadult',
            name='tip_contract',
        ),
        migrations.RemoveField(
            model_name='anuntadult',
            name='tip_job',
        ),
    ]
