# Generated by Django 3.1.5 on 2022-01-24 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='name',
            new_name='name_room',
        ),
    ]
