# Generated by Django 3.1.5 on 2022-01-11 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anuntadult',
            name='capacitate_motor',
        ),
    ]
