# Generated by Django 3.1.5 on 2021-07-15 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anunt',
            name='categoria',
        ),
    ]
