# Generated by Django 3.1.5 on 2022-01-11 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_anuntadult_caroserie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anuntadult',
            name='capacitate_motor',
            field=models.CharField(db_column='capacitate_motor', max_length=264, null=True),
        ),
    ]
