# Generated by Django 3.1.5 on 2021-07-27 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_remove_anunt_categoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorii',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categorii_copil', models.CharField(choices=[('C', 'Carti'), ('J', 'Jucarii'), ('H', 'Haine')], max_length=256)),
                ('categorii_adult', models.CharField(choices=[('A', 'Auto'), ('I', 'Imobiliare'), ('M', 'Moda'), ('A_C', 'Animale_de_companie'), ('T', 'Telefoane'), ('E', 'Electrocasnice')], max_length=256)),
                ('slug', models.SlugField()),
            ],
        ),
    ]
