# Generated by Django 3.1.5 on 2022-01-08 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_auto_20220108_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anuntadult',
            name='pret',
            field=models.FloatField(default=1, null=True),
        ),
    ]
