# Generated by Django 3.1.5 on 2021-07-29 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0003_categorii'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Anunt',
        ),
        migrations.DeleteModel(
            name='Categorii',
        ),
    ]
