# Generated by Django 3.1.5 on 2021-07-29 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0004_auto_20210729_1203'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnuntAdult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titlul', models.CharField(max_length=264)),
                ('descriere', models.TextField(max_length=624)),
                ('categorie_adult', models.CharField(choices=[('A', 'Auto'), ('I', 'Imobiliare'), ('M', 'Moda'), ('A_C', 'Animale_de_companie'), ('T', 'Telefoane'), ('E', 'Electrocasnice')], max_length=264)),
                ('telefon', models.FloatField()),
                ('email', models.EmailField(max_length=254)),
                ('imagine', models.ImageField(upload_to='')),
                ('localizare', models.CharField(max_length=264)),
            ],
        ),
        migrations.CreateModel(
            name='AnuntCopil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titlul', models.CharField(max_length=264)),
                ('descriere', models.TextField(max_length=624)),
                ('categorie_copil', models.CharField(choices=[('C', 'Carti'), ('J', 'Jucarii'), ('H', 'Haine')], max_length=264)),
                ('telefon', models.FloatField()),
                ('email', models.EmailField(max_length=254)),
                ('imagine', models.ImageField(upload_to='')),
                ('localizare', models.CharField(max_length=264)),
            ],
        ),
    ]
