# Generated by Django 3.1.5 on 2022-01-08 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0004_auto_20220108_1838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anuntadult',
            name='pret',
            field=models.IntegerField(default=1, null=True),
        ),
    ]
