# Generated by Django 3.1.5 on 2022-04-18 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0004_remove_commentadult_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anuntadult',
            name='email',
            field=models.EmailField(max_length=264, null=True),
        ),
    ]
