# Generated by Django 3.1.5 on 2022-01-13 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0005_auto_20220113_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anuntadult',
            name='pret',
            field=models.CharField(choices=[('Vand', 'Vand'), ('Schimb', 'Schimb')], max_length=264, null=True),
        ),
    ]
