# Generated by Django 3.1.5 on 2021-09-08 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0005_anuntadult_anuntcopil'),
    ]

    operations = [
        migrations.CreateModel(
            name='AjutorSiContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume', models.CharField(max_length=264)),
                ('email', models.EmailField(max_length=254)),
                ('descriere', models.TextField(max_length=624)),
            ],
        ),
        migrations.AlterField(
            model_name='anuntcopil',
            name='imagine',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
