# Generated by Django 3.1.5 on 2022-01-09 20:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('my_app', '0005_auto_20220108_1954'),
    ]

    operations = [
        migrations.AddField(
            model_name='anuntadult',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='anuntadult',
            name='pret',
            field=models.CharField(default=1, max_length=264, null=True),
        ),
    ]
