# Generated by Django 3.1.5 on 2021-09-14 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0006_auto_20210908_1205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anuntcopil',
            name='categorie_copil',
            field=models.CharField(choices=[('C', 'Carti'), ('J', 'Jucarii'), ('H', 'Haine'), ('B', 'Biciclete')], max_length=264),
        ),
        migrations.AlterField(
            model_name='anuntcopil',
            name='telefon',
            field=models.PositiveIntegerField(),
        ),
    ]
