# Generated by Django 3.1.5 on 2022-01-10 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0006_auto_20220109_2212'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anuntadult',
            name='user',
        ),
    ]
