# Generated by Django 3.1.5 on 2021-09-15 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0007_auto_20210914_1836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anuntadult',
            name='telefon',
            field=models.IntegerField(),
        ),
    ]
