# Generated by Django 3.1.5 on 2022-01-10 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0007_remove_anuntadult_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anuntadult',
            name='caroserie',
        ),
    ]
