# Generated by Django 3.1.5 on 2022-04-22 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0007_auto_20220422_2328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anuntadult',
            name='pret',
            field=models.CharField(max_length=264, null=True),
        ),
    ]
