# Generated by Django 3.1.5 on 2022-07-14 18:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('my_app', '0008_auto_20220422_2329'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='copil',
            name='parola',
        ),
        migrations.RemoveField(
            model_name='copil',
            name='prenume',
        ),
        migrations.AddField(
            model_name='copil',
            name='profile_pic',
            field=models.ImageField(blank=True, default='images/user2.png', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='copil',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
