# Generated by Django 3.1.5 on 2022-07-14 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0009_auto_20220714_2148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='copil',
            name='profile_pic',
            field=models.ImageField(blank=True, default='user2.png', null=True, upload_to=''),
        ),
    ]
