# Generated by Django 3.1.5 on 2021-11-02 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0009_auto_20211101_1108'),
    ]

    operations = [
        migrations.CreateModel(
            name='MesajCopil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mesaj', models.TextField(max_length=624)),
            ],
        ),
        migrations.RemoveField(
            model_name='anuntcopil',
            name='pret',
        ),
    ]
