# Generated by Django 3.1.5 on 2021-11-02 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0010_auto_20211102_1114'),
    ]

    operations = [
        migrations.AddField(
            model_name='anuntcopil',
            name='pret',
            field=models.FloatField(null=True, unique=True),
        ),
    ]
