# Generated by Django 3.1.5 on 2021-11-02 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0011_anuntcopil_pret'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anuntcopil',
            name='pret',
            field=models.FloatField(blank=True, null=True, unique=True),
        ),
    ]
