# Generated by Django 3.1.5 on 2022-07-20 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0011_auto_20220718_2058'),
    ]

    operations = [
        migrations.RenameField(
            model_name='anuntcopil',
            old_name='favorit',
            new_name='favorite',
        ),
    ]
