# Generated by Django 3.1.5 on 2021-11-03 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0012_auto_20211102_1210'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversatie_Copil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conversatie_copil', models.CharField(max_length=264)),
            ],
        ),
    ]
