# Generated by Django 3.1.5 on 2022-07-24 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0013_mesaj_copil'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adult',
            old_name='emailul',
            new_name='email',
        ),
        migrations.RemoveField(
            model_name='adult',
            name='parola',
        ),
        migrations.AddField(
            model_name='adult',
            name='profile_pic',
            field=models.ImageField(default='user2.png', null=True, upload_to=''),
        ),
    ]
