# Generated by Django 3.1.5 on 2021-11-03 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0013_conversatie_copil'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Conversatie_Copil',
        ),
    ]
