# Generated by Django 3.1.5 on 2021-11-05 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0014_delete_conversatie_copil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anuntadult',
            name='localizare',
            field=models.CharField(choices=[('Alba', 'Alba'), ('Arad', 'Arad'), ('Arges', 'Arges'), ('Bacau', 'Bacau'), ('Bihor', 'Bihor'), ('Bistrita-Nasaud', 'Bistrita-Nasaud'), ('Botosani', 'Botosani'), ('Braila', 'Braila'), ('Brasov', 'Brasov'), ('Buzau', 'Buzau'), ('Calarasi', 'Calarasi'), ('Caras-Severin', 'Caras-Severin'), ('Cluj', 'Cluj'), ('Constanta', 'Constanta'), ('Covasna', 'Covasna'), ('Dambovita', 'Dambovita'), ('Dolj', 'Dolj'), ('Galati', 'Galati'), ('Giurgiu', 'Giurgiu'), ('Gorj', 'Gorj'), ('Harghita', 'Harghita'), ('Hunedoara', 'Hunedoara'), ('Ialomita', 'Ialomita'), ('Iasi', 'Iasi'), ('Ilfov', 'Ilfov'), ('Maramures', 'Maramures'), ('Mehedinti', 'Mehedinti'), ('Mures', 'Mures'), ('Neamt', 'Neamt'), ('Olt', 'Olt'), ('Prahova', 'Prahova'), ('Salaj', 'Salaj'), ('Satu Mare', 'Satu Mare'), ('Sibiu', 'Sibiu'), ('Suceava', 'Suceava'), ('Teleorman', 'Teleorman'), ('Timis', 'Timis'), ('Tulcea', 'Tulcea'), ('Valcea', 'Valcea'), ('Vaslui', 'Vaslui'), ('Vrancea', 'Vrancea')], max_length=264),
        ),
        migrations.AlterField(
            model_name='anuntcopil',
            name='localizare',
            field=models.CharField(choices=[('Alba', 'Alba'), ('Arad', 'Arad'), ('Arges', 'Arges'), ('Bacau', 'Bacau'), ('Bihor', 'Bihor'), ('Bistrita-Nasaud', 'Bistrita-Nasaud'), ('Botosani', 'Botosani'), ('Braila', 'Braila'), ('Brasov', 'Brasov'), ('Buzau', 'Buzau'), ('Calarasi', 'Calarasi'), ('Caras-Severin', 'Caras-Severin'), ('Cluj', 'Cluj'), ('Constanta', 'Constanta'), ('Covasna', 'Covasna'), ('Dambovita', 'Dambovita'), ('Dolj', 'Dolj'), ('Galati', 'Galati'), ('Giurgiu', 'Giurgiu'), ('Gorj', 'Gorj'), ('Harghita', 'Harghita'), ('Hunedoara', 'Hunedoara'), ('Ialomita', 'Ialomita'), ('Iasi', 'Iasi'), ('Ilfov', 'Ilfov'), ('Maramures', 'Maramures'), ('Mehedinti', 'Mehedinti'), ('Mures', 'Mures'), ('Neamt', 'Neamt'), ('Olt', 'Olt'), ('Prahova', 'Prahova'), ('Salaj', 'Salaj'), ('Satu Mare', 'Satu Mare'), ('Sibiu', 'Sibiu'), ('Suceava', 'Suceava'), ('Teleorman', 'Teleorman'), ('Timis', 'Timis'), ('Tulcea', 'Tulcea'), ('Valcea', 'Valcea'), ('Vaslui', 'Vaslui'), ('Vrancea', 'Vrancea')], max_length=264),
        ),
    ]
