# Generated by Django 3.1.5 on 2022-10-03 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0014_auto_20220724_1027'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentadult',
            name='post',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
        migrations.DeleteModel(
            name='Room',
        ),
        migrations.DeleteModel(
            name='RoomMember',
        ),
        migrations.AlterField(
            model_name='adult',
            name='profile_pic',
            field=models.ImageField(default='profile_pic.png', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='copil',
            name='profile_pic',
            field=models.ImageField(blank=True, default='profile_pic.png', null=True, upload_to=''),
        ),
        migrations.DeleteModel(
            name='CommentAdult',
        ),
    ]
