# Generated by Django 3.1.5 on 2021-11-08 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0015_auto_20211105_1739'),
    ]

    operations = [
        migrations.AddField(
            model_name='anuntadult',
            name='pret',
            field=models.FloatField(blank=True, null=True, unique=True),
        ),
    ]
