# Generated by Django 3.1.5 on 2022-10-09 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0015_auto_20221003_1822'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anuntadult',
            name='imagine6',
        ),
        migrations.RemoveField(
            model_name='anuntcopil',
            name='imagine6',
        ),
    ]
