# Generated by Django 3.1.5 on 2021-11-08 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0016_anuntadult_pret'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchBarCopil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search', models.CharField(choices=[((('Alba', 'Alba'), ('Arad', 'Arad'), ('Arges', 'Arges'), ('Bacau', 'Bacau'), ('Bihor', 'Bihor'), ('Bistrita-Nasaud', 'Bistrita-Nasaud'), ('Botosani', 'Botosani'), ('Braila', 'Braila'), ('Brasov', 'Brasov'), ('Buzau', 'Buzau'), ('Calarasi', 'Calarasi'), ('Caras-Severin', 'Caras-Severin'), ('Cluj', 'Cluj'), ('Constanta', 'Constanta'), ('Covasna', 'Covasna'), ('Dambovita', 'Dambovita'), ('Dolj', 'Dolj'), ('Galati', 'Galati'), ('Giurgiu', 'Giurgiu'), ('Gorj', 'Gorj'), ('Harghita', 'Harghita'), ('Hunedoara', 'Hunedoara'), ('Ialomita', 'Ialomita'), ('Iasi', 'Iasi'), ('Ilfov', 'Ilfov'), ('Maramures', 'Maramures'), ('Mehedinti', 'Mehedinti'), ('Mures', 'Mures'), ('Neamt', 'Neamt'), ('Olt', 'Olt'), ('Prahova', 'Prahova'), ('Salaj', 'Salaj'), ('Satu Mare', 'Satu Mare'), ('Sibiu', 'Sibiu'), ('Suceava', 'Suceava'), ('Teleorman', 'Teleorman'), ('Timis', 'Timis'), ('Tulcea', 'Tulcea'), ('Valcea', 'Valcea'), ('Vaslui', 'Vaslui'), ('Vrancea', 'Vrancea')), (('Alba', 'Alba'), ('Arad', 'Arad'), ('Arges', 'Arges'), ('Bacau', 'Bacau'), ('Bihor', 'Bihor'), ('Bistrita-Nasaud', 'Bistrita-Nasaud'), ('Botosani', 'Botosani'), ('Braila', 'Braila'), ('Brasov', 'Brasov'), ('Buzau', 'Buzau'), ('Calarasi', 'Calarasi'), ('Caras-Severin', 'Caras-Severin'), ('Cluj', 'Cluj'), ('Constanta', 'Constanta'), ('Covasna', 'Covasna'), ('Dambovita', 'Dambovita'), ('Dolj', 'Dolj'), ('Galati', 'Galati'), ('Giurgiu', 'Giurgiu'), ('Gorj', 'Gorj'), ('Harghita', 'Harghita'), ('Hunedoara', 'Hunedoara'), ('Ialomita', 'Ialomita'), ('Iasi', 'Iasi'), ('Ilfov', 'Ilfov'), ('Maramures', 'Maramures'), ('Mehedinti', 'Mehedinti'), ('Mures', 'Mures'), ('Neamt', 'Neamt'), ('Olt', 'Olt'), ('Prahova', 'Prahova'), ('Salaj', 'Salaj'), ('Satu Mare', 'Satu Mare'), ('Sibiu', 'Sibiu'), ('Suceava', 'Suceava'), ('Teleorman', 'Teleorman'), ('Timis', 'Timis'), ('Tulcea', 'Tulcea'), ('Valcea', 'Valcea'), ('Vaslui', 'Vaslui'), ('Vrancea', 'Vrancea'))), ((('Carti', 'Carti'), ('Jucarii', 'Jucarii'), ('Haine', 'Haine'), ('Articole sportive', 'Articole sportive'), ('Schimburi', 'Schimburi'), ('Mama si copil', 'Mama si copil')), (('Carti', 'Carti'), ('Jucarii', 'Jucarii'), ('Haine', 'Haine'), ('Articole sportive', 'Articole sportive'), ('Schimburi', 'Schimburi'), ('Mama si copil', 'Mama si copil')))], max_length=264, null=True)),
            ],
        ),
    ]
