# Generated by Django 3.1.5 on 2022-10-09 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0016_auto_20221009_1138'),
    ]

    operations = [
        migrations.AddField(
            model_name='anuntadult',
            name='model',
            field=models.CharField(max_length=264, null=True),
        ),
        migrations.AddField(
            model_name='anuntadult',
            name='nr_usi',
            field=models.CharField(max_length=264, null=True),
        ),
    ]
