# Generated by Django 3.1.5 on 2021-11-09 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0017_searchbarcopil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchbarcopil',
            name='search',
            field=models.CharField(max_length=264, null=True),
        ),
    ]
