# Generated by Django 3.1.5 on 2021-11-10 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0019_auto_20211109_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anuntadult',
            name='categorie_adult',
            field=models.CharField(choices=[('Auto, moto si ambarcatiuni', 'Auto, moto si ambarcatiuni'), ('Piese auto', 'Piese auto'), ('Agro si industrie', 'Agro si industrie'), ('Imobiliare', 'Imobiliare'), ('Moda si frumusete', 'Moda si frumusete'), ('Electronice si electrocasnice', 'Electronice si electrocasnice'), ('Servicii si echipamente firma', 'Servicii si echipamente firma'), ('Animale de companie', 'Animale de companie'), ('Locuri de munca', 'Locuri de munca'), ('Sport, timp liber si Hobby', 'Sport, timp liber si Hobby'), ('Mici intreprinzatori autohtoni', 'Mici intreprinzatori autohtoni'), ('Mama si copil', 'Mama si copil')], max_length=264),
        ),
    ]
