# Generated by Django 3.1.5 on 2021-11-13 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0022_afacere_adresa'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviciu',
            name='expeperienta_porfesionala',
            field=models.TextField(max_length=1200, null=True),
        ),
    ]
