# Generated by Django 3.1.5 on 2021-11-13 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0023_serviciu_expeperienta_porfesionala'),
    ]

    operations = [
        migrations.RenameField(
            model_name='serviciu',
            old_name='expeperienta_porfesionala',
            new_name='experienta_profesionala',
        ),
    ]
