# Generated by Django 3.1.5 on 2021-11-13 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0024_auto_20211113_1959'),
    ]

    operations = [
        migrations.AddField(
            model_name='afacere',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='serviciu',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
