# Generated by Django 3.1.5 on 2021-11-15 19:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('my_app', '0027_auto_20211115_2003'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='copil',
            name='email',
        ),
        migrations.RemoveField(
            model_name='copil',
            name='nume',
        ),
        migrations.RemoveField(
            model_name='copil',
            name='parola',
        ),
        migrations.RemoveField(
            model_name='copil',
            name='prenume',
        ),
        migrations.AddField(
            model_name='copil',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
