# Generated by Django 3.1.5 on 2021-12-04 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0031_auto_20211204_1210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anuntadult',
            name='pret',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
