# Generated by Django 3.1.5 on 2021-12-10 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0033_auto_20211204_1242'),
    ]

    operations = [
        migrations.AddField(
            model_name='anuntcopil',
            name='moneda',
            field=models.CharField(blank=True, max_length=264, null=True),
        ),
        migrations.AlterField(
            model_name='anuntcopil',
            name='titlul',
            field=models.CharField(max_length=264, null=True),
        ),
    ]
