# Generated by Django 3.1.5 on 2021-12-11 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0035_auto_20211211_1917'),
    ]

    operations = [
        migrations.AddField(
            model_name='anuntadult',
            name='imagine2',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='anuntadult',
            name='imagine3',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='anuntadult',
            name='imagine4',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='anuntadult',
            name='imagine5',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='anuntadult',
            name='imagine6',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
