# Generated by Django 3.1.5 on 2021-12-11 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0036_auto_20211211_2009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anuntcopil',
            name='pret',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
