# Generated by Django 3.1.5 on 2021-12-11 20:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('my_app', '0037_auto_20211211_2226'),
    ]

    operations = [
        migrations.AddField(
            model_name='anuntadult',
            name='favorit',
            field=models.ManyToManyField(blank=True, null=True, related_name='favorit', to=settings.AUTH_USER_MODEL),
        ),
    ]
