# Generated by Django 3.1.5 on 2021-12-11 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0039_auto_20211211_2249'),
    ]

    operations = [
        migrations.AddField(
            model_name='afacere',
            name='imagine2',
            field=models.ImageField(blank=True, null=True, unique=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='afacere',
            name='imagine3',
            field=models.ImageField(blank=True, null=True, unique=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='afacere',
            name='imagine4',
            field=models.ImageField(blank=True, null=True, unique=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='afacere',
            name='imagine5',
            field=models.ImageField(blank=True, null=True, unique=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='afacere',
            name='imagine6',
            field=models.ImageField(blank=True, null=True, unique=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='afacere',
            name='descriere',
            field=models.TextField(max_length=9000, null=True),
        ),
        migrations.AlterField(
            model_name='afacere',
            name='tipul_afacerii',
            field=models.CharField(choices=[('Cabinet medical', 'Cabinet medical'), ('Cabinet psihologic', 'Cabinet psihologic'), ('Cafenea', 'Cafenea'), ('Cofetarie', 'Cofetarie'), ('Constructii', 'Constructii'), ('Hotel', 'Hotel'), ('Fast-Food-uri', 'Fast-Food-uri'), ('Pensiune', 'Pensiune'), ('Restaurant', 'Restaurant'), ('Service Auto', 'Service Auto')], max_length=264),
        ),
    ]
