# Generated by Django 3.1.5 on 2021-12-11 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0040_auto_20211212_0042'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviciu',
            name='imagine2',
            field=models.ImageField(blank=True, null=True, unique=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='serviciu',
            name='imagine3',
            field=models.ImageField(blank=True, null=True, unique=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='serviciu',
            name='imagine4',
            field=models.ImageField(blank=True, null=True, unique=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='serviciu',
            name='imagine5',
            field=models.ImageField(blank=True, null=True, unique=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='serviciu',
            name='imagine6',
            field=models.ImageField(blank=True, null=True, unique=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='serviciu',
            name='descriere',
            field=models.TextField(max_length=9000, null=True),
        ),
        migrations.AlterField(
            model_name='serviciu',
            name='experienta_profesionala',
            field=models.TextField(max_length=9000, null=True),
        ),
    ]
