# Generated by Django 3.1.5 on 2021-12-12 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0042_auto_20211212_1206'),
    ]

    operations = [
        migrations.AddField(
            model_name='afacere',
            name='numele_firmei',
            field=models.CharField(max_length=264, null=True),
        ),
    ]
