# Generated by Django 3.1.5 on 2021-12-12 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0043_afacere_numele_firmei'),
    ]

    operations = [
        migrations.AddField(
            model_name='anuntadult',
            name='numele_anuntului',
            field=models.CharField(max_length=264, null=True),
        ),
        migrations.AddField(
            model_name='serviciu',
            name='numele_serviciului',
            field=models.CharField(max_length=264, null=True),
        ),
    ]
