# Generated by Django 3.1.5 on 2021-12-12 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0044_auto_20211212_1245'),
    ]

    operations = [
        migrations.AddField(
            model_name='anuntcopil',
            name='imagine2',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='anuntcopil',
            name='imagine3',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='anuntcopil',
            name='imagine4',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='anuntcopil',
            name='imagine5',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='anuntcopil',
            name='imagine6',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='anuntcopil',
            name='numele_anuntului',
            field=models.CharField(max_length=264, null=True),
        ),
    ]
