# Generated by Django 3.1.5 on 2021-12-15 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0045_auto_20211212_1258'),
    ]

    operations = [
        migrations.AddField(
            model_name='afacere',
            name='telefon',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='afacere',
            name='tipul_afacerii',
            field=models.CharField(choices=[('Cabinet medical', 'Cabinet medical'), ('Cabinet psihologic', 'Cabinet psihologic'), ('Cafenea', 'Cafenea'), ('Cofetarie', 'Cofetarie'), ('Constructii', 'Constructii'), ('Frizerii', 'Frizerii'), ('Hotel', 'Hotel'), ('Fast-Food-uri', 'Fast-Food-uri'), ('Pensiune', 'Pensiune'), ('Restaurant', 'Restaurant'), ('Saloane de coafura', 'Saloane de coafura'), ('Service Auto', 'Service Auto')], max_length=264),
        ),
    ]
