# Generated by Django 3.1.5 on 2021-12-16 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0046_auto_20211215_1932'),
    ]

    operations = [
        migrations.CreateModel(
            name='MesajAfaceri',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume', models.CharField(max_length=264, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('mesaj', models.TextField(max_length=9000, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='ajutorsicontact',
            name='descriere',
            field=models.TextField(max_length=9000),
        ),
        migrations.AlterField(
            model_name='anuntadult',
            name='descriere',
            field=models.TextField(max_length=9000),
        ),
        migrations.AlterField(
            model_name='anuntcopil',
            name='descriere',
            field=models.TextField(max_length=9000),
        ),
        migrations.AlterField(
            model_name='mesajadult',
            name='mesaj',
            field=models.TextField(max_length=9000),
        ),
        migrations.AlterField(
            model_name='mesajcopil',
            name='mesaj',
            field=models.TextField(max_length=9000),
        ),
        migrations.AlterField(
            model_name='serviciu',
            name='tipul_serviciului',
            field=models.CharField(choices=[('Contabilitate', 'Contabilitate'), ('Consultanta', 'Consultanta'), ('Digital Marketing', 'Digital Marketing'), ('Grafic si Design', 'Grafic si Design'), ('Meditatii', 'Meditatii'), ('Programare si tehnologie', 'Programare si tehnologie'), ('Video si animatii', 'Video si animatii')], max_length=264),
        ),
    ]
