# Generated by Django 3.1.5 on 2021-12-17 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0047_auto_20211216_2119'),
    ]

    operations = [
        migrations.CreateModel(
            name='MesajServiciu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume', models.CharField(max_length=264, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('mesaj', models.TextField(max_length=9000, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='serviciu',
            name='telefon',
            field=models.IntegerField(null=True),
        ),
    ]
