# Generated by Django 3.1.5 on 2021-12-21 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0048_auto_20211217_1850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anuntadult',
            name='subcategorie_adult',
            field=models.CharField(max_length=264, null=True),
        ),
    ]
