# Generated by Django 3.1.5 on 2021-12-21 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0049_auto_20211221_1914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anuntadult',
            name='categorie_adult',
            field=models.CharField(max_length=264, null=True),
        ),
    ]
