# Generated by Django 3.1.5 on 2021-12-21 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0050_auto_20211221_1920'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anuntadult',
            name='categorie_adult',
        ),
    ]
