# Generated by Django 3.1.5 on 2021-12-21 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0053_auto_20211221_1948'),
    ]

    operations = [
        migrations.AddField(
            model_name='anuntadult',
            name='categorie_a',
            field=models.CharField(max_length=264, null=True),
        ),
    ]
