# Generated by Django 3.1.5 on 2021-12-21 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0054_anuntadult_categorie_a'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anuntadult',
            name='categorie_a',
        ),
        migrations.AlterField(
            model_name='anuntadult',
            name='categorie_adult',
            field=models.CharField(max_length=264, null=True, unique=True),
        ),
    ]
