# Generated by Django 3.1.5 on 2021-12-21 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0058_auto_20211221_2008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anuntadult',
            name='categorie_adult',
            field=models.CharField(max_length=264, null=True),
        ),
    ]
