# Generated by Django 3.1.5 on 2021-12-22 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0059_auto_20211221_2203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anuntadult',
            name='categorie_adult',
            field=models.CharField(blank=True, max_length=264, null=True),
        ),
    ]
