# Generated by Django 3.1.5 on 2021-12-22 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0061_anuntadult_categorie_a'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anuntadult',
            name='categorie_a',
        ),
    ]
